=== Rosalioalfre2/TPI115-Guia-32/xmlvalido_GRUPO06/dtd_externa/tareas.dtd
<!-- documento dtd -->
<!ELEMENT equipos (equipo)+>
<!ELEMENT equipo ( facultad,carrera,formacion,profesor, actividad_evaluada,informacion, estudiante)>
<!ELEMENT facultad (#PCDATA)>
    <!ATTLIST  facultad  nombre  CDATA #REQUIRED>
    <!ATTLIST  facultad  codigo  CDATA #REQUIRED>
<!ELEMENT carrera (#PCDATA)>
    <!ATTLIST  carrera nombrec  CDATA #REQUIRED>
    <!ATTLIST  carrera  codigoc  CDATA #REQUIRED>
<!ELEMENT formacion (#PCDATA)>
    <!ATTLIST  formacion  materia  (GT | GD | GL) #REQUIRED>
<!ELEMENT profesor (#PCDATA)>
    <!ATTLIST  profesor  identificaciÃ³n  CDATA #IMPLIED>
<!ELEMENT actividad_evaluada (#PCDATA)>
 <!ATTLIST  actividad_evaluada  tarea CDATA #REQUIRED>
    <!ATTLIST  actividad_evaluada  porcentaje  CDATA #REQUIRED>  
<!ELEMENT informacion (#PCDATA)>
<!ELEMENT estudiante (coordinador, integrante1, integrante2, integrante3)>
<!ELEMENT coordinador (carnet, (nombre|apellido)*)>

<!ELEMENT carnet (#PCDATA)>
  <!ATTLIST  carnet coordinador  CDATA  #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
  <!ATTLIST  nombre coordinador  CDATA  #REQUIRED>
<!ELEMENT apellido (#PCDATA)>
  <!ATTLIST  apellido coordinador  CDATA  #REQUIRED>


<!ELEMENT integrante1 (carnet1, (nombre1|apellido1)*)>
<!ELEMENT carnet1 (#PCDATA)>
  <!ATTLIST  carnet1 estudiante1  CDATA  #REQUIRED>
<!ELEMENT nombre1 (#PCDATA)>
  <!ATTLIST  nombre1 estudiante1  CDATA  #REQUIRED>
<!ELEMENT apellido1 (#PCDATA)>
  <!ATTLIST  apellido1 estudiante1  CDATA  #REQUIRED>

<!ELEMENT integrante2 (carnet2, (nombre2|apellido2)*)>
<!ELEMENT carnet2 (#PCDATA)>
  <!ATTLIST  carnet2 estudiante2  CDATA  #REQUIRED>
<!ELEMENT nombre2 (#PCDATA)>
  <!ATTLIST  nombre2 estudiante2  CDATA  #REQUIRED>
<!ELEMENT apellido2 (#PCDATA)>
  <!ATTLIST  apellido2 estudiante2  CDATA  #REQUIRED>


<!ELEMENT integrante3 (carnet3, (nombre3|apellido3)*)>
<!ELEMENT carnet3 (#PCDATA)>
  <!ATTLIST  carnet3 estudiante3  CDATA  #REQUIRED>
<!ELEMENT nombre3 (#PCDATA)>
  <!ATTLIST  nombre3 estudiante3  CDATA  #REQUIRED>
<!ELEMENT apellido3 (#PCDATA)>
  <!ATTLIST  apellido3 estudiante3  CDATA  #REQUIRED> 
  <!ATTLIST equipos lang (es|en|fr) "es" copyright CDATA #FIXED "Universidad de El Salvador">

=== Rosalioalfre2/TPI115-Guia-32/xmlvalido_GRUPO06/dtd_externa/tareas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="tareas.css" ?>
<!DOCTYPE equipos SYSTEM "tareas.dtd">

<equipos>

      <equipo>

          <facultad nombre="Facultad de Ingenieria y Arquitectura" codigo="001">FIA</facultad>
          <carrera nombrec="Ingenieria de sistemas Informaticos" codigoc="001">Sistemas</carrera>
          <formacion materia="GT"></formacion>
          <profesor></profesor>
          <actividad_evaluada  tarea="tarea investigacion" porcentaje="20%"></actividad_evaluada>
          <informacion></informacion>
          <estudiante coordinador="Grupo01" carnet="55555" nombre ="Juan" apellido ="Che" >Coordinador1</estudiante>
          <estudiante integrante="Grupo01" carnet="78748654" nombre ="Ko" apellido ="La" >Integrante1</estudiante>
          <estudiante integrante="Grupo01" carnet="2752" nombre ="Ko" apellido ="La" >Integrante1</estudiante>
          <estudiante integrante="Grupo01" carnet="4545" nombre ="Ka" apellido ="pa" >Integrante2</estudiante>
          <estudiante integrante="Grupo01" carnet="542" nombre ="Po" apellido ="Le" >Integrante3</estudiante>
          

      </equipo>

          <equipo>

          <facultad></facultad>
          <carrera>Industrial</carrera>
          <formacion  materia="GD"></formacion>
          <profesor></profesor>
          <actividad_evaluada></actividad_evaluada>
          <informacion></informacion>
          <estudiante coordinador="Grupo02" carnet="888888" nombre ="Maria" apellido ="Cho" >Coordinador2</estudiante>
         <estudiante integrante="Grupo02" carnet="2452" nombre ="dsao" apellido ="Lsda" >Integrante1</estudiante>
          <estudiante integrante="Grupo02" carnet="42452" nombre ="Kasda" apellido ="pasda" >Integrante2</estudiante>
          <estudiante integrante="Grupo02" carnet="544522" nombre ="Poasd" apellido ="Lsade" >Integrante3</estudiante>
          

      </equipo>
</equipos>
